eqlabs/starknet-validator-attestation

src/main.rs, src/signer.rs
Reqwest defaults to no timeout, which can lead to problems.
=> fix(signer): use a 60s timeout for remote signer requests

README.md
Now that the Staking v2 contracts are deployed on Sepolia, we need to update the README file with the new contract addresses.
=> chore(README): update Sepolia contract addresses

.github/workflows/release.yml
This commit adds a GitHub Actions workflow that creates a draft release and uploads a compiled binary as an artifact to that release whenever a new tag is pushed to the repository.
=> chore(github): add release workflow

Cargo.lock, Cargo.toml, Dockerfile, src/jsonrpc.rs, src/main.rs
The default HTTP transport in starknet-providers creates a HTTP client with no timeouts. Since this could block our state machine indefinitely we now set a timeout of 30 seconds.
Unfortunately starknet-rs uses an older version of reqwest so we have to add an additional dependency to our Cargo.toml to be able to set the timeout. This is a temporary workaround until `starknet-rs` upgrades to a newer version of `reqwest`.
=> fix(jsonrpc): create JSON-RPC client with a HTTP timeout of 30 seconds

.github/workflows/release.yml
Ubuntu 20.04 is no longer available.
=> chore(github): bump release binary builder to Ubuntu 22.04

src/jsonrpc.rs, src/main.rs, src/state.rs
Including some incorrect uses of `.unwrap()` that might lead to panics upon encountering certain JSON-RPC errors.
=> fix: fix some lint issues

README.md, examples/signer.rs, src/jsonrpc.rs, src/signer.rs
Instead of sending a `transaction_hash` along with the transaction, the clear signing API now receives the `chain_id` and the `transaction` only. This forces the signer implementation to recalculate the transaction hash value itself (for which it needs the chain ID).
=> fix(signer): make remote signing API compatible with Juno

README.md, src/jsonrpc.rs, src/main.rs
To simplify configuration this PR adds default values for staking and attestation contract addresses for Sepolia (and partially for mainnet).
This works by querying the chain ID via JSON-RPC and using the [well-known addresses](https://docs.starknet.io/resources/chain-info/#staking) both for Sepolia and mainnet.
Addresses specified explicitly override these defaults.
=> feat: add defaults for staking/attestation contract addresses

src/main.rs
When misconfiguring the environment variable the error message printed was just telling the user that parsing a felt has failed:
```
13:17:57.047655Z  INFO starknet_validator_attestation: Using local signer
Error: Failed to create Felt from string
```
This commit adds a context to the error message, so that the user can see that the error is related to the private key environment variable:
```
2025-04-29T13:40:34.961888Z  INFO starknet_validator_attestation: Using local signer
Error: Parsing private key
Caused by:
Failed to create Felt from string
```
=> fix(main): add anyhow context when parsing private key env var

README.md, src/jsonrpc.rs, src/signer.rs
When using a remote signer, the attestation tool should not force that the signature returned is an ECDSA signature (`r` and `s` values).
Since on the remote signer API we're expecting the signature as an array of felts, the attestation tool should just take this array directly and use it as a signature for the transaction.
Some account contracts _do_ support non-ECDSA signatures, or use a signature encoding scheme that is not compatible with the ECDSA scheme used by the OpenZeppelin account contract. (Braavos for example uses a signature that's longer than just two felts.)
=> feat: add support for non-ECDSA remote signatures

src/state.rs
The `Debug` implementation for `anyhow::Error` logs the whole error chain, so instead of just logging that the transaction submission failed we now also log the _actual_ underlying error in detail (like: attestation already done, or attestation out of window).
=> chore: log detailed transaction submission error

README.md, src/metrics_exporter.rs, src/state.rs
The new metrics counts the number of epochs where we have failed to attest.
Closes #26
=> feat(metrics): add new metric for missed epochs

README.md, src/jsonrpc.rs, src/main.rs, src/metrics_exporter.rs, src/state.rs
Adds a new Prometheus metric `validator_attestation_operational_account_balance_strk` to monitor the current STRK balance of the operational account.
Currently stakers need to manually monitor their operational account balance to avoid attestation failures due to insufficient funds for transaction fees.
- Added `get_strk_balance()` method to query STRK token balance via ERC20 contract
- New metric updates on startup and at the start of each new epoch
- Simplified STRK contract addresses (same for mainnet and sepolia)
- Added proper error handling and logging
- **New metric**: `validator_attestation_operational_account_balance_strk` (gauge, in STRK units)
- **Efficient updates**: Balance refreshed on startup and once per epoch only
- **Test support**: Mock implementation for unit tests …
=> Add STRK balance metric

src/state.rs
Edit: this PR has been split into two: the logging improvements, which is kept here. State machine related changes will be done in a different PR, independently of this one.
This PR improves how `StarknetRpcClient` manages nonces and makes the attestation state transitions more robust.
* Added `Mutex` to safely manage `current_nonce`, so transactions don't clash when multiple are sent in a short time.
* Replaced the `Attesting` state with two clearer states: `AttestationWindowActive` and `AttestationSubmitted`. This helps avoid duplicate submissions and better reflects what's happening.
* Improved error handling for expired attestation windows and added metrics for missed epochs.
* After a successful attestation, the state now correctly moves to `WaitingForNextEpoch`.
* Updated test cases …
=> feat(attestation): improve logging

src/state.rs
The `validator_attestation_missed_epochs_count` metric was incorrectly incrementing when the attestator restarted or updated after an attestation window had expired, even if the attestation was already completed successfully.
**Reproduction scenario:**
1. Validator successfully attests a block
2. Wait 20-30 blocks 
3. Restart the attestator
4. The metric incorrectly shows the epoch as "missed" even though it was actually attested
The state machine was incrementing the missed epochs counter without checking if an attestation was already completed for the current epoch. This happened in two places:
1. In `Attesting` state when attestation window expires
2. In `AttestationSubmitted` state when waiting for confirmation times out
Added `attestation_done_in_current_epoch()` checks before …
=> fix validator_attestation_missed_epochs_count metric bug

src/state.rs
Fixed typo: `ckeck_and_submit_attestation` → `check_and_submit_attestation`
**What was changed:**
- Corrected spelling error in function name (missing 'h' in 'check')
**Impact:**
- No functional changes, code readability improvement
=> fix typo after #PR39

src/state.rs
```
Improve transaction hash logging format in warn messages
```
Transaction hashes in error logs were displayed as decimal numbers instead of hexadecimal format, making them difficult to read and debug.
```
transaction_hash=5124521129427308090043450866476784141884011571369475561623939911145490936811
```
```
transaction_hash=0x3с9b456732327abc6def0123786789abcdef0123456789abcdef01234567891234
```
- Changed `%transaction_hash` to `?transaction_hash` in warn logging
- Affects warn "Attestation transaction has reverted" messages
- Makes transaction hashes readable and copy-pasteable for debugging
=> improve transaction hash logging

src/state.rs
Same like #43 
```
2025-08-08T07:41:09.617096Z DEBUG starknet_validator_attestation::state: Sending attestation transaction block_hash=1692128594018699135270783997152132567241324676163502873655836942529590157564
```
=> improve block hash logging

Cargo.lock, Cargo.toml, src/events.rs, src/jsonrpc.rs, src/state.rs
This change upgrades starknet-rs and makes the required changes to support JSON-RPC API 0.9.0.
We're now explicitly querying state at the _latest_ block and ignoring pre-confirmed data so that we get the same finality semantics as we did have with JSON-RPC 0.8.0 and _pending_ in earlier versions.
=> feat: use JSON-RPC API 0.9.0

Cargo.lock, Cargo.toml
In particular, this PR upgrades starknet-rs to the final 0.17.0 release.
=> chore: upgrade starknet-rs and other dependencies

README.md, justfile, src/metrics_exporter.rs, src/state.rs
The new metric tracks the total number of attestation confirmation events received. Useful in cases where a starker is running multiple instances of the attestation tool.
=> feat(metrics): add new metric for total confirmations observed
